### PR TITLE
add more clarity

### PR DESCRIPTION
**Pull request by nikoflora**
ps kinda sucks tbh /j

### CODE REVIEW

**Review by nikoflora — COMMENTED** [review]
tbh i agree with this, this should get added into main teyvatps

**Comment by Shichiha** [comment]
it's not good to insult php 
issues should be discussed somewhere else too 🥺 

anyways this PR is also low-effort and stuff 😁

**Comment by nikoflora** [comment]
shichi are you high?

**Comment by lilmayofuksu** [comment]
balls

**Pull request closed without merging**
